### ISSUE TITLE
Crashed upon installation

### ISSUE THREAD

**Issue by pbrilius** [dflock/ulauncher-xfwm-workspace-switcher#1]
Message: undefined
Error Name: undefined
Type: undefined

Stacktrace:
```
undefined
```

**Comment by dflock** [comment]
This isn't a lot to go on.

What's your OS, version of Ulauncher, version of wmctrl, version of Python?

Do other ulauncher plugins install & work fine?

**Comment by MagnusCaesar** [comment]
Message: 'com.github.dflock.ulauncher-xfwm-workspace-switcher'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 201, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 447, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.9/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.dflock.ulauncher-xfwm-workspace-switcher'

```

**Comment by MagnusCaesar** [comment]
Same issue of crashing after installation with the above error message

**Comment by dflock** [comment]
Not trying to pass the buck, but that looks like "uLauncher couldn't find the plugin", rather than "Plugin crashed" - i.e. the problem (& solution) are something to do with uLauncher installing plugins.

**Comment by dflock** [comment]
Or maybe this: https://github.com/Ulauncher/Ulauncher/issues/716

**Comment by dflock** [comment]
OK, so I've just added checking for `wmctrl` at startup, so if that was the cause the extension shouldn't crash anymore, it will print out: "Missing Dependency: wmctrl not found on $PATH".

**Comment by MagnusCaesar** [comment]
Thanks! It works now, was missing the dependency indeed, did not know that
